### ISSUE TITLE
Pakketap

### ISSUE THREAD

**Issue by linact** [TTK4145/elevator-server#1]
@WheelBarrow2

**Comment by ghost** [comment]
**Legge til** sudo iptables -A INPUT -m statistic --mode random --probability 0.15 -j DROP
**Fjerne** sudo iptables -D OUTPUT 1
**Piazza** http://piazza.com/ntnu.no/spring2017/ttk4145

**Comment by ghost** [comment]
**Oppdatert kommando** sudo iptables -A INPUT -p udp -m statistic --mode random --probability 0.15 -j DROP
