### ISSUE TITLE
Server shuts down when losing connection (simulator doesn't)

### ISSUE THREAD

**Issue by kahole** [TTK4145/elevator-server#3]
When disconnecting from an Elevator Server the server proceeds to shut itself down.

The simulator does not have this behaviour. This is an issue specifically if you rely on restarting your program at some fault e.g.

**Comment by kahole** [comment]
This if-statement and it's body seems to be enforcing this behaviour:

https://github.com/TTK4145/elevator-server/blob/6cd21cf8ba36cc5e468034f2cb050a911fc5b450/src/main.rs#L270-L273

**Comment by kjetilkjeka** [comment]
As a quickfix you can start the ElevatorServer in a loop.

Leave the issue open and we will fix this for next year, we don't want to change anything at this point.

**Comment by klasbo** [comment]
This was fixed with the D version in 2019
